### ISSUE TITLE
Remove Celery dependency

### ISSUE THREAD

**Issue by brylie** [CiviWiki/OpenCiviWiki#925]
Split from #918 

We currently use Celery to handle asynchronous tasks such as sending on boarding emails. At this stage of the project, Celery may be too complicated for our needs.

Remove Celery and ensure that tasks that previously relied on Celery will still function without it.

**Comment by a7madnassar** [comment]
@brylie please assign this issue to me. I already have the changes done. Thanks

**Comment by a7madnassar** [comment]
@brylie I implemented the fix successfully. The only problem is I always push to my develop branch forked from the main `develop` branch. Currently, my branch is ahead of the `develop` branch because of my commit for upgrading Django to 3.2. I created a pull request for that task and it was never merged. I just downloaded the current `develop` branch and ran the server and the app is broken, because the Django version was upgraded to 3.2.4 without the needed changes in templates.

My last pull request will have the fix for all of this trouble. I will submit it now, and this is a working version of the app running on Django 3.2.4.

**Comment by brylie** [comment]
Closed by #933

**Comment by pscheid2** [comment]
celery is still listed in our requirements.txt and we still have some code referencing that old email sending logic.

**Comment by a7madnassar** [comment]
@brylie and @pscheid2 the task was created mainly to address the registration failure issue. The commit includes the fix for that and more without removing Celery completely. Because it might be re-integrated in the future, I chose not to remove the current Celery app and the related tasks. I will remove any references to them for now.

**Comment by pscheid2** [comment]
It's my preference to remove the dependency entirely if we do not plan on using it for now, but open to other input if we think keeping it around for something other than the registration flow is valuable.

**Comment by brylie** [comment]
I agree with @pscheid2. If we aren't actively using any code or dependency, we should remove it from the project.

**Comment by a7madnassar** [comment]
@brylie and @pscheid2 I will work on removing Celery entirely then. I will submit a pull request once I'm done.

**Comment by a7madnassar** [comment]
@brylie I just submitted a pull request for removing Celery completely from the app.
